### ISSUE TITLE
helm "podAnnotations" cannot applied

### ISSUE THREAD

**Issue by githubeto** [grafana/k6-operator#477] opened 2024-10-08 03:08 UTC
### Brief summary

helm chart values
```
podAnnotations:
  "karpenter.sh/do-not-disrupt": "true"
```

install commands:
```
helm upgrade k6-operator -f k6-operator-values.yaml grafana/k6-operator
```

error log:

```
Error: UPGRADE FAILED: values don't meet the specifications of the schema(s) in the following chart(s):
k6-operator:
- podAnnotations: Additional property karpenter.sh/do-not-disrupt is not allowed
````

### k6-operator version or image

0.0.17

### Helm chart version (if applicable)

k6-operator-3.9.0

### TestRun / PrivateLoadZone YAML

not.

### Steps to reproduce the problem

-

### Expected behaviour

helm install.

### I also tried these.

```
podAnnotations:
  karpenter.sh/do-not-disrupt: "true"
```

```
podAnnotations:
  karpenter.sh/do-not-disrupt: true
```

**Comment by flowjo-shaunr** [comment] 2024-10-17 23:11
I am also experiencing this issue. It seems that even the sample yaml file ([customAnnotationsAndLabels.yaml](https://github.com/grafana/k6-operator/blob/main/charts/k6-operator/samples/customAnnotationsAndLabels.yaml)) cannot be used with the values schema.

```bash
% helm template -f test.yaml grafana/k6-operator
coalesce.go:220: warning: cannot overwrite table with non table for k6-operator.manager.env (map[])
Error: values don't meet the specifications of the schema(s) in the following chart(s):
k6-operator:
- (root): Additional property certManager is not allowed
- customLabels: Additional property customized-labels is not allowed
- manager.readinessProbe: Additional property successThreshold is not allowed
- manager.readinessProbe: Additional property timeoutSeconds is not allowed
- manager.readinessProbe: Additional property failureThreshold is not allowed
- manager.readinessProbe: Additional property httpGet is not allowed
- manager.readinessProbe: Additional property initialDelaySeconds is not allowed
- manager.readinessProbe: Additional property periodSeconds is not allowed
- manager.env: Invalid type. Expected: object, given: array
- manager.image: Additional property name is not allowed
- manager.livenessProbe: Additional property failureThreshold is not allowed
- manager.livenessProbe: Additional property httpGet is not allowed
- manager.livenessProbe: Additional property initialDelaySeconds is not allowed
- manager.livenessProbe: Additional property periodSeconds is not allowed
- manager.livenessProbe: Additional property successThreshold is not allowed
- manager.livenessProbe: Additional property timeoutSeconds is not allowed
- podLabels: Additional property environment is not allowed
- podLabels: Additional property owner is not allowed
- podAnnotations: Additional property customized-annotation is not allowed
- affinity: Additional property nodeAffinity is not allowed
- authProxy.resources: Additional property limits is not allowed
- authProxy.resources: Additional property requests is not allowed
- customAnnotations: Additional property customized-annotation is not allowed
- nodeSelector: Additional property disktype is not allowed
- tolerations: Invalid type. Expected: object, given: array
```

Why is `"additionalProperties": false` for all of these `object`s (`customAnnotations`, `customLabels`, etc) without any properties defined?

**Comment by stawr93** [comment] 2024-10-22 12:01
Got same issue. Rolled back to helm chart version 3.8.0 - works fine

**Comment by yorugac** [comment] 2024-10-25 06:08
👋  @githubeto, sorry for the delay; but I believe this is a duplicate of https://github.com/grafana/k6-operator/issues/471 ?

**Comment by yorugac** [comment] 2024-10-31 12:52
@flowjo-shaunr, 
> - (root): Additional property certManager is not allowed

This part was fixed in https://github.com/grafana/k6-operator/pull/480

The rest of errors is expected to be fixed the same as in https://github.com/grafana/k6-operator/issues/471#issuecomment-2449758399

So closing this in favor of https://github.com/grafana/k6-operator/issues/471. Please watch that one: I'll update there once a new release is up.

**Closed by yorugac** 2024-10-31 12:52 UTC
Labels: bug
