### ISSUE TITLE
Failure on finding service with default K8s cluster domain

### ISSUE THREAD

**Issue by nhatnam1198** [grafana/k6-operator#327] opened 2023-10-31 10:23 UTC
### Brief summary

K8s cluster domain is set to `cluster.local` by default. However, our K8s cluster has changed this config to others which caused the operator not to be able to find the service of an object whose kind is `K6`. Hence, the `StartJob` can not be started as expected.

The code to find the K8s service is hardcoded in the `StartJobs` function.
https://github.com/grafana/k6-operator/blob/7ce63b1790f30f6b9693e8a4a2f0fed0bb47c2ac/controllers/k6_start.go#L20

### k6-operator version or image

https://github.com/grafana/k6-operator/releases/tag/v0.0.11

### K6 YAML

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "4"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"control-plane":"controller-manager"},"name":"k6-operator-controller-manager","namespace":"k6-operator-system"},"spec":{"replicas":1,"selector":{"matchLabels":{"control-plane":"controller-manager"}},"template":{"metadata":{"labels":{"control-plane":"controller-manager"}},"spec":{"containers":[{"args":["--secure-listen-address=0.0.0.0:8443","--upstream=http://127.0.0.1:8080/","--logtostderr=true","--v=10"],"image":"gcr.io/kubebuilder/kube-rbac-proxy:v0.8.0","name":"kube-rbac-proxy","ports":[{"containerPort":8443,"name":"https"}]},{"args":["--metrics-addr=127.0.0.1:8080","--enable-leader-election"],"command":["/manager"],"image":"registry-gitlab.zalopay.vn/top/docker-images/k6-extended:v1.1","name":"manager","resources":{"limits":{"cpu":"100m","memory":"100Mi"},"requests":{"cpu":"100m","memory":"50Mi"}}}],"serviceAccountName":"k6-operator-controller","terminationGracePeriodSeconds":10}}}}
  creationTimestamp: "2023-10-31T04:14:56Z"
  generation: 4
  labels:
    control-plane: controller-manager
  name: k6-operator-controller-manager
  namespace: k6-operator-system
  resourceVersion: "313185098"
  uid: 710fda5c-1c3d-43fd-b09b-08e14a505a10
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      control-plane: controller-manager
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        control-plane: controller-manager
    spec:
      containers:
      - args:
        - --secure-listen-address=0.0.0.0:8443
        - --upstream=http://127.0.0.1:8080/
        - --logtostderr=true
        - --v=10
        image: gcr.io/kubebuilder/kube-rbac-proxy:v0.8.0
        imagePullPolicy: IfNotPresent
        name: kube-rbac-proxy
        ports:
        - containerPort: 8443
          name: https
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      - args:
        - --metrics-addr=127.0.0.1:8080
        - --enable-leader-election
        command:
        - /manager
        image: ghcr.io/grafana/k6-operator
        imagePullPolicy: IfNotPresent
        name: manager
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 50Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: registry-gitlab-secret
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: k6-operator-controller
      serviceAccountName: k6-operator-controller
      terminationGracePeriodSeconds: 10
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2023-10-31T04:22:05Z"
    lastUpdateTime: "2023-10-31T04:22:05Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2023-10-31T04:14:56Z"
    lastUpdateTime: "2023-10-31T10:19:59Z"
    message: ReplicaSet "k6-operator-controller-manager-64c65bdbc5" has successfully
      progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 4
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
```

### Steps to reproduce the problem

Use `make deploy` as mentioned in README.md

### Expected behaviour

K6 Operator is able to find the required service

### Actual behaviour

Not able to find the service via DNS record due to hardcoded URL

### Operator Log:
```bash
2023-10-31T10:21:07Z ERROR controllers.K6 failed to get status from k6-sample-service 
github.com/grafana/k6-operator/controllers.isServiceReady                                       
/workspace/controllers/k6_start.go:23                                                       
github.com/grafana/k6-operator/controllers.StartJobs

```

**Comment by yorugac** [comment] 2024-01-12 09:05
@nhatnam1198, this issue got a bit lost in the torrent of others, but it's actually a duplicate of an older issue #233 which was recently fixed. Please try the latest version of k6-operator: it should work. If it doesn't, please re-open with additional details. Thanks.

**Closed by yorugac** 2024-01-12 09:05 UTC
Labels: bug
